name: Cache Environment Variable

on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        run: echo "ENV_VARIABLE=my-value" >> $GITHUB_ENV
        # Make sure to replace "my-value" with the desired value

      - name: Cache environment variable
        id: cache-env
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/env
          key: env-variable

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Restore environment variable cache
        id: restore-env
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/env
          key: env-variable

      - name: Use environment variable in job2
        run: |
          echo "The value of ENV_VARIABLE is ${{ steps.restore-env.outputs.paths }}"
