name: CI / CD Learning

on:
  pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Using node.js ${{ matrix.node-version }}      
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }} 

      - name: npm install
        run: npm ci   