name: CI / CD Learning

on:
  workflow_dispatch

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Using node.js ${{ matrix.node-version }}      
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }} 

      - name: npm install
        run: npm ci  

      - name: Tests
        run: npm test

  sonarqube:
    name: Build
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}         