name: Semantic Release

on:
  workflow_dispatch

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload SDK
        uses: actions/upload-artifact@v2   
        with:
          name: SDK
          path: build/
      - name: Download contents
        uses: actions/download-artifact@v2
        with:
          name: SDK         
      - name: Create semantic release using release-it
        id: create_release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}